### PR TITLE
Updated code for full implementation

### PR DESCRIPTION
**Pull request by hash00x1**

### CODE REVIEW

**Review by hash00x1 — COMMENTED** [review]
looking good. Ready for next steps.

**Review by hash00x1 — COMMENTED** [review]
looks good

**Review by MelGGit — APPROVED** [review]

**Review by hash00x1 — COMMENTED** [review]
looking good

**Review by hash00x1 — COMMENTED** [review]
looking good

**Review by hash00x1 — COMMENTED** [review]
looking good

**Review by hash00x1 — COMMENTED** [review]
looking good

**Pull request merged**
